Sprint 1
Iker-elorrieta/ADTeam4 pull request #1
Opened 2020-10-15 17:46 UTC by JulenSmith

Reto Sprint 1

2020-10-16 08:56 UTC, Iker-elorrieta requested changes
Realizar los cambios que os comento de cara al siguiente Sprint. Son 3 los principales aspectos a mejorar:

1. Throws

2. Uso de estructuras en java (Objeto Libro y estructura de almacenamiento)

3. Mostrar de forma uniforme los objetos.

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +		Lectorcsv Lc = new Lectorcsv();
Lectorcsv debe crearse una vez en todas las pruebas

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +			} catch (Exception e) {
No puede haber un catch en una prueba

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +			} catch (Exception e) {
catch

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +		Lectortxt LT = new Lectortxt();
Lectortxt fuera de prueba ya que se reutiliza

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +	void testLectorTxt() throws IOException {
No puede hacer throw una prueba

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +	void testLectorTxtFallo() throws IOException  {
throw

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +	void testLectorXML() throws FileNotFoundException   {
throw

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +	void testmain3() throws IOException {
throw

2020-10-16 08:56 UTC, Iker-elorrieta commented on test/mainTest/testMain.java
> +	    Scanner teclado = new Scanner(System.in);
La clase Scanner teclado puede ser declarada fuera

2020-10-16 08:56 UTC, Iker-elorrieta commented on listalibros.txt
> +N� 1 : Harry Potter
Faltan atributos de los libros

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/LectorXml.java
> +	public static boolean LeerArchivoXML(String archivo)throws FileNotFoundException {
No throw

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/LectorXml.java
> +
No se guarda en ninguna estructura de Java para poder mostrarlo

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/Lectorcsv.java
> +	public static boolean lectorcsv(String archivo) throws FileNotFoundException {
No puede haber un throw, hay que controlar la excepción

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/Lectortxt.java
> +	public static boolean lectorTxt(String enlace) throws FileNotFoundException  {
No puede haber un throw

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/principal/Programa.java
> +	public static void main(String[] args) throws IOException {
Main sin IOException

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/principal/Programa.java
> +	public static boolean iniciarPrograma(Scanner teclado) throws IOException {
Throw no correcto

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/Lectortxt.java
> +
No existe una estructura de guardado en Java, se muestra directamente, sin diferenciar atributos

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/Lectorcsv.java
> +
No se hace nada en el error

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/comunes/Lectorcsv.java
> +
Se reemplaza una y otra vez el libro, no se mete en ninguna estructura el libro creado

2020-10-16 08:56 UTC, Iker-elorrieta commented on src/principal/Programa.java
> +					Lectortxt.lectorTxt("listalibros.txt");
Las varibles de los libros deberían ir en un final String en este caso.

2020-10-19 13:47 UTC, Garikoitz7 commented on test/mainTest/testMain.java
> +		Lectortxt LT = new Lectortxt();
hecho

2020-10-19 13:47 UTC, Garikoitz7 commented on test/mainTest/testMain.java
> +	void testLectorTxt() throws IOException {
hecho

2020-10-19 13:48 UTC, Garikoitz7 commented on test/mainTest/testMain.java
> +	void testLectorTxtFallo() throws IOException  {
hecho

2020-10-19 14:10 UTC, Garikoitz7 commented on listalibros.txt
> +N� 1 : Harry Potter
hecho

2020-10-19 14:11 UTC, Garikoitz7 commented on src/comunes/Lectortxt.java
> +	public static boolean lectorTxt(String enlace) throws FileNotFoundException  {
hecho

2020-10-20 23:51 UTC, davidBFuentes commented on src/principal/Programa.java
> +					Lectortxt.lectorTxt("listalibros.txt");
Hecho.

2020-10-20 23:52 UTC, davidBFuentes commented on src/comunes/Lectorcsv.java
> +
Hecho.

2020-10-20 23:55 UTC, davidBFuentes commented on src/comunes/Lectorcsv.java
> +
Hecho

2020-10-20 23:55 UTC, davidBFuentes commented on src/principal/Programa.java
> +	public static boolean iniciarPrograma(Scanner teclado) throws IOException {
Hecho

2020-10-20 23:55 UTC, davidBFuentes commented on src/principal/Programa.java
> +	public static void main(String[] args) throws IOException {
Hecho

2020-10-20 23:56 UTC, davidBFuentes commented on src/comunes/Lectorcsv.java
> +	public static boolean lectorcsv(String archivo) throws FileNotFoundException {
Hecho

2020-10-20 23:56 UTC, davidBFuentes commented on test/mainTest/testMain.java
> +	    Scanner teclado = new Scanner(System.in);
Hecho.

2020-10-20 23:57 UTC, davidBFuentes commented on test/mainTest/testMain.java
> +	void testmain3() throws IOException {
Hecho.

2020-10-20 23:57 UTC, davidBFuentes commented on test/mainTest/testMain.java
> +			} catch (Exception e) {
Hecho.

2020-10-20 23:57 UTC, davidBFuentes commented on test/mainTest/testMain.java
> +			} catch (Exception e) {
Hecho.

2020-10-21 00:01 UTC, davidBFuentes commented on test/mainTest/testMain.java
> +		Lectorcsv Lc = new Lectorcsv();
Hecho.

2020-10-21 11:03 UTC, Iker-elorrieta requested changes
Os queda cambiar el metodo de lectura .txt se repiten lineas de codigo innecesarios.

Con eso, ya estaría.

2020-10-21 11:03 UTC, Iker-elorrieta commented on src/comunes/Lectortxt.java
> +					String array[] = linea.split(": ");
String array[] = linea.split(": "); toda la linea

2020-10-21 13:12 UTC, JulenSmith commented on test/mainTest/testMain.java
> +	void testLectorXML() throws FileNotFoundException   {
Done

2020-10-21 13:12 UTC, JulenSmith commented on src/comunes/LectorXml.java
> +	public static boolean LeerArchivoXML(String archivo)throws FileNotFoundException {
done

2020-10-21 13:12 UTC, JulenSmith commented on src/comunes/LectorXml.java
> +
done

2020-10-21 18:51 UTC, Iker-elorrieta approved these changes

2020-10-21 18:51 UTC, merged